# -*- coding: utf-8 -*-
"""ASSIGNMENT8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Wg3JuVi-sllLZMTnbF6CbtGSGqVJOO6H
"""

# -*- coding: utf-8 -*-
"""Assignment-8.ipynb
Automatically generated by Colaboratory.
Original file is located at
    https://colab.research.google.com/drive/1MzVYYLJBg4EagDwG1793x0kYmiBAR6w9
"""

import numpy as np
# Original matrix
A = np.array([[2,1],[1,1]])
print("Original matrix:")
print(A)
result =  np.linalg.inv(A)
print("Inverse of the said matrix:")
print(result)
  
# Decomposition of the said matrix
q, r = np.linalg.qr(A)
print('\nQ:\n', q)
print('\nR:\n', r)